spring:
  application:
    name: k8s4cloud
  jackson:
    default-property-inclusion: NON_NULL



logging:
  level:
    ind.syu: debug
    io.kubernetes: info
    org:
      springframework: debug


server:
  port: 8002


self:
  kubeConfigPath: /kubeconfig
  tokenExpireMin: 300
  jwtkey: 1KP0SsvENi7Uz1oQc07aXTL7kpQG5jBNIybqr60AlD4
  activitiRedisApprovalMessageChannel: receiveApprovalSresult
  allowOrigin: "*"
  allowMethods: GET,PATCH,PUT,POST,DELETE,OPTIONS
  allowHeads: access-token,_token,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,Referer,Sec-Fetch-Mode
  ignorePath:
    - ^/kube
    - ^/pod-terminal

