spring:
  application:
    name: k8s4cloud

  jackson:
    default-property-inclusion: NON_NULL



logging:
  level:
    ind.syu: debug
    io.kubernetes: info
    org:
      springframework: debug

server:
  port: 8002


self:
  registryUrl: http://192.168.50.28:5000
  #registryUrl: http://127.0.0.1:5000

  #officalRegistryUrl: https://index.docker.io
  officalRegistryUrl: https://dockerhub.azk8s.cn
  #officalRegistryUrl: https://registry.docker-cn.com
  authRegistryUrl: https://auth.docker.io
  httpProxy: 127.0.0.1:1087
  tempFileDir: /tmp/registry/
  enableProxy: true
  needProxyUrl:
    - https://index.docker.io

  kubeConfigPath: /Users/syu/.kube/config-company
  #kubeConfigPath: /Users/syu/.kube/config
  tokenExpireMin: 300
  jwtkey: 1KP0SsvENi7Uz1oQc07aXTL7kpQG5jBNIybqr60AlD4
  activitiRedisApprovalMessageChannel: receiveApprovalSresult
  allowOrigin: "*"
  allowMethods: GET,PATCH,PUT,POST,DELETE,OPTIONS
  allowHeads: access-token,_token,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,Referer,Sec-Fetch-Mode
  ignorePath:
    - ^/kube
    - ^/v2/kube
    - ^/pod-terminal
    - ^/registry

