/*
 * docker registry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.V1ManifestResultFsLayers;

/**
 * V1ManifestResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-03-20T09:01:06.524239+08:00[Asia/Shanghai]")
public class V1ManifestResult {
  public static final String SERIALIZED_NAME_SCHEMA_VERSION = "schemaVersion";
  @SerializedName(SERIALIZED_NAME_SCHEMA_VERSION)
  private Integer schemaVersion;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TAG = "tag";
  @SerializedName(SERIALIZED_NAME_TAG)
  private String tag;

  public static final String SERIALIZED_NAME_FS_LAYERS = "fsLayers";
  @SerializedName(SERIALIZED_NAME_FS_LAYERS)
  private List<V1ManifestResultFsLayers> fsLayers = null;


  public V1ManifestResult schemaVersion(Integer schemaVersion) {
    
    this.schemaVersion = schemaVersion;
    return this;
  }

   /**
   * Get schemaVersion
   * @return schemaVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getSchemaVersion() {
    return schemaVersion;
  }


  public void setSchemaVersion(Integer schemaVersion) {
    this.schemaVersion = schemaVersion;
  }


  public V1ManifestResult name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1ManifestResult tag(String tag) {
    
    this.tag = tag;
    return this;
  }

   /**
   * Get tag
   * @return tag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTag() {
    return tag;
  }


  public void setTag(String tag) {
    this.tag = tag;
  }


  public V1ManifestResult fsLayers(List<V1ManifestResultFsLayers> fsLayers) {
    
    this.fsLayers = fsLayers;
    return this;
  }

  public V1ManifestResult addFsLayersItem(V1ManifestResultFsLayers fsLayersItem) {
    if (this.fsLayers == null) {
      this.fsLayers = new ArrayList<V1ManifestResultFsLayers>();
    }
    this.fsLayers.add(fsLayersItem);
    return this;
  }

   /**
   * Get fsLayers
   * @return fsLayers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1ManifestResultFsLayers> getFsLayers() {
    return fsLayers;
  }


  public void setFsLayers(List<V1ManifestResultFsLayers> fsLayers) {
    this.fsLayers = fsLayers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1ManifestResult v1ManifestResult = (V1ManifestResult) o;
    return Objects.equals(this.schemaVersion, v1ManifestResult.schemaVersion) &&
        Objects.equals(this.name, v1ManifestResult.name) &&
        Objects.equals(this.tag, v1ManifestResult.tag) &&
        Objects.equals(this.fsLayers, v1ManifestResult.fsLayers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(schemaVersion, name, tag, fsLayers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1ManifestResult {\n");
    sb.append("    schemaVersion: ").append(toIndentedString(schemaVersion)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    fsLayers: ").append(toIndentedString(fsLayers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

